# Block size of ABF file
ABF2.BlockSize = 512

# Definition of ABF2 header
ABF2.Header.field = c("fFileSignature", #0
                     "fFileVersionNumber1", #4
                     "fFileVersionNumber2", #5
                     "fFileVersionNumber3", #6
                     "fFileVersionNumber4", #7
                     "uFileInfoSize", #8
                     "lActualEpisodes", #12
                     "uFileStartDate", #16
                     "uFileStartTimeMS", #20
                     "uStopwatchTime", #24
                     "nFileType", #28
                     "nDataFormat", #30
                     "nSimultaneousScan", #32
                     "nCRCEnable", #34
                     "uFileCRC", #36
                     "FileGUID1", #40
                     "FileGUID2", #48
                     "uCreatorVersion", #56
                     "uCreatorNameIndex", #60
                     "uModifierVersion", #64
                     "uModifierNameIndex", #68
                     "uProtocolPathIndex") #72
ABF2.Header.ctype = c("string",
                     "int8",
                     "int8",
                     "int8",
                     "int8",
                     "uint32",
                     "uint32",
                     "uint32",
                     "uint32",
                     "uint32",
                     "int16",
                     "int16",
                     "int16",
                     "int16",
                     "uint32",
                     "int64",
                     "int64",
                     "uint32",
                     "uint32",
                     "uint32",
                     "uint32",
                     "uint32")
ABF2.Header.ssize = c(4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
ABF2.Header.def = data.frame(field = ABF2.Header.field,
                             ctype = ABF2.Header.ctype,
                             ssize = ABF2.Header.ssize)

#Definition of section info
ABF2.SectionInfo.field = c("uBlockIndex",
                           "uBytes",
                           "llNumEntries")
ABF2.SectionInfo.ctype = c("uint32",
                           "uint32",
                           "int64")
ABF2.SectionInfo.ssize = c(0, 0, 0)
ABF2.SectionInfo.def = data.frame(field = ABF2.SectionInfo.field,
                                  ctype = ABF2.SectionInfo.ctype,
                                  ssize = ABF2.SectionInfo.ssize)
ABF2.SectionInfoList = c("Protocol",
                         "ADC",
                         "DAC",
                         "Epoch",
                         "ADCPerDAC",
                         "EpochPerDAC",
                         "UserList",
                         "StatsRegion",
                         "Math",
                         "Strings",
                         "Data",
                         "Tag",
                         "Scope",
                         "Delta",
                         "VoiceTag",
                         "SynchArray",
                         "Annotation",
                         "Stats")

# Sections
ABF2.Protocol.field = c( "nOperationMode",
                        "fADCSequenceInterval",
                        "bEnableFileCompression",
                        "sUnused1",
                        "uFileCompressionRatio",
                        "fSynchTimeUnit",
                        "fSecondsPerRun",
                        "lNumSamplesPerEpisode",
                        "lPreTriggerSamples",
                        "lEpisodesPerRun",
                        "lRunsPerTrial",
                        "lNumberOfTrials",
                        "nAveragingMode",
                        "nUndoRunCount",
                        "nFirstEpisodeInRun",
                        "fTriggerThreshold",
                        "nTriggerSource",
                        "nTriggerAction",
                        "nTriggerPolarity",
                        "fScopeOutputInterval",
                        "fEpisodeStartToStart",
                        "fRunStartToStart",
                        "lAverageCount",
                        "fTrialStartToStart",
                        "nAutoTriggerStrategy",
                        "fFirstRunDelayS",
                        "nChannelStatsStrategy",
                        "lSamplesPerTrace",
                        "lStartDisplayNum",
                        "lFinishDisplayNum",
                        "nShowPNRawData",
                        "fStatisticsPeriod",
                        "lStatisticsMeasurements",
                        "nStatisticsSaveStrategy",
                        "fADCRange",
                        "fDACRange",
                        "lADCResolution",
                        "lDACResolution",
                        "nExperimentType",
                        "nManualInfoStrategy",
                        "nCommentsEnable",
                        "lFileCommentIndex",
                        "nAutoAnalyseEnable",
                        "nSignalType",
                        "nDigitalEnable",
                        "nActiveDACChannel",
                        "nDigitalHolding",
                        "nDigitalInterEpisode",
                        "nDigitalDACChannel",
                        "nDigitalTrainActiveLogic",
                        "nStatsEnable",
                        "nStatisticsClearStrategy",
                        "nLevelHysteresis",
                        "lTimeHysteresis",
                        "nAllowExternalTags",
                        "nAverageAlgorithm",
                        "fAverageWeighting",
                        "nUndoPromptStrategy",
                        "nTrialTriggerSource",
                        "nStatisticsDisplayStrategy",
                        "nExternalTagType",
                        "nScopeTriggerOut",
                        "nLTPType",
                        "nAlternateDACOutputState",
                        "nAlternateDigitalOutputState",
                        "fCellID1",
                        "fCellID2",
                        "fCellID3",
                        "nDigitizerADCs",
                        "nDigitizerDACs",
                        "nDigitizerTotalDigitalOuts",
                        "nDigitizerSynchDigitalOuts",
                        "nDigitizerType",
                        "sUnused")
ABF2.Protocol.ctype = c("int16",
                       "float",
                       "int8",
                       "unused",
                       "uint32",
                       "float",
                       "float",
                       "int32",
                       "int32",
                       "int32",
                       "int32",
                       "int32",
                       "int16",
                       "int16",
                       "int16",
                       "float",
                       "int16",
                       "int16",
                       "int16",
                       "float",
                       "float",
                       "float",
                       "int32",
                       "float",
                       "int16",
                       "float",
                       "int16",
                       "int32",
                       "int32",
                       "int32",
                       "int16",
                       "float",
                       "int32",
                       "int16",
                       "float",
                       "float",
                       "int32",
                       "int32",
                       "int16",
                       "int16",
                       "int16",
                       "int32",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int32",
                       "int16",
                       "int16",
                       "float",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "float",
                       "float",
                       "float",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "int16",
                       "unused"  )
ABF2.Protocol.ssize = c(0, 0, 0, 3,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 0, 0, 0,
                       0, 304)
ABF2.Protocol.def = data.frame(field = ABF2.Protocol.field,
                              ctype = ABF2.Protocol.ctype,
                              ssize = ABF2.Protocol.ssize)

ABF2.Math.field = c("nMathEnable", "nMathExpression", "uMathOperatorIndex", "uMathUnitsIndex",
                   "fMathUpperLimit", "fMathLowerLimit", "nMathADCNum1", "nMathADCNum2",
                   "sUnused1", "fMathK1", "fMathK2", "fMathK3",
                   "fMathK4", "fMathK5", "fMathK6", "sUnused2")
ABF2.Math.ctype = c("int16", "int16", "uint32", "uint32",
                   "float", "float", "int16", "int16",
                   "unused", "float", "float", "float",
                   "float", "float", "float", "unused")
ABF2.Math.ssize = c(0, 0, 0, 0,
                   0, 0, 0, 0,
                   16, 0, 0, 0,
                   0, 0, 0, 64)
ABF2.Math.def = data.frame(field = ABF2.Math.field,
                          ctype = ABF2.Math.ctype,
                          ssize = ABF2.Math.ssize)

ABF2.ADC.field = c("nADCNum",
                  "nTelegraphEnable",
                  "nTelegraphInstrument",
                  "fTelegraphAdditGain",
                  "fTelegraphFilter",
                  "fTelegraphMembraneCap",
                  "nTelegraphMode",
                  "fTelegraphAccessResistance",
                  "nADCPtoLChannelMap",
                  "nADCSamplingSeq",
                  "fADCProgrammableGain",
                  "fADCDisplayAmplification",
                  "fADCDisplayOffset",
                  "fInstrumentScaleFactor",
                  "fInstrumentOffset",
                  "fSignalGain",
                  "fSignalOffset",
                  "fSignalLowpassFilter",
                  "fSignalHighpassFilter",
                  "nLowpassFilterType",
                  "nHighpassFilterType",
                  "fPostProcessLowpassFilter",
                  "nPostProcessLowpassFilterType",
                  "bEnabledDuringPN",
                  "nStatsChannelPolarity",
                  "lADCChannelNameIndex",
                  "lADCUnitsIndex",
                  "sUnused")
ABF2.ADC.ctype = c( "int16",
                   "int16",
                   "int16",
                   "float",
                   "float",
                   "float",
                   "int16",
                   "float",
                   "int16",
                   "int16",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "char",
                   "char",
                   "float",
                   "char",
                   "int8",
                   "int16",
                   "int32",
                   "int32",
                   "unused")
ABF2.ADC.ssize = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46)
ABF2.ADC.def = data.frame(field = ABF2.ADC.field,
                         ctype = ABF2.ADC.ctype,
                         ssize = ABF2.ADC.ssize)

ABF2.DAC.field = c("nDACNum",
                  "nTelegraphDACScaeFactorEnable",
                  "fInstrumentHoldingLevel",
                  "fDACScaleFactor",
                  "fDACHoldingLevel",
                  "fDACCalibrationFactor",
                  "fDACCalibrationOffset",
                  "lDACChannelNameIndex",
                  "lDACChannelUnitsIndex",
                  "lDACFilePtr",
                  "lDACFileNumEpisodes",
                  "nWaveformEnable",
                  "nWaveformSource",
                  "nInterEpisodeLevel",
                  "fDACFileScale",
                  "fDACFileOffset",
                  "lDACFileEpisodeNum",
                  "nDACFileADCNum",
                  "nConditEnable",
                  "lConditNumPulses",
                  "fBaselineDuration",
                  "fBaselineLevel",
                  "fStepDuration",
                  "fStepLevel",
                  "fPostTrainPeriod",
                  "fPostTrainLevel",
                  "nMembTestEnable",
                  "nLeakSubtractType",
                  "nPNPolarity",
                  "fPNHoldingLevel",
                  "nPNNumADCChannels",
                  "nPNPosition",
                  "nPNNumPulses",
                  "fPNSettlingTime",
                  "fPNInterpulse",
                  "nLTPUsageOfDAC",
                  "nLTPPresynapticPulses",
                  "lDACFilePathIndex",
                  "fMembTestPreSettlingTimeMS",
                  "fMembTestPostSettlingTimeMS",
                  "nLeakSubtractADCIndex",
                  "sUnused")
ABF2.DAC.ctype = c( "int16",
                   "int16",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "int32",
                   "int32",
                   "int32",
                   "int32",
                   "int16",
                   "int16",
                   "int16",
                   "float",
                   "float",
                   "int32",
                   "int16",
                   "int16",
                   "int32",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "float",
                   "int16",
                   "int16",
                   "int16",
                   "float",
                   "int16",
                   "int16",
                   "int16",
                   "float",
                   "float",
                   "int16",
                   "int16",
                   "int32",
                   "float",
                   "float",
                   "int16",
                   "unused" )
ABF2.DAC.ssize = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 124)
ABF2.DAC.def = data.frame(field = ABF2.DAC.field,
                         ctype = ABF2.DAC.ctype,
                         ssize = ABF2.DAC.ssize)

ABF2.EpochPerDAC.field = c("nEpochNum",
                          "nDACNum",
                          "nEpochType",
                          "fEpochInitLevel",
                          "fEpochLevelInc",
                          "lEpochInitDuration",
                          "lEpochDurationInc",
                          "lEpochPulsePeriod",
                          "lEpochPulseWidth",
                          "sUnused")
ABF2.EpochPerDAC.ctype = c( "int16",
                           "int16",
                           "int16",
                           "float",
                           "float",
                           "int32",
                           "int32",
                           "int32",
                           "int32",
                           "unused" )
ABF2.EpochPerDAC.ssize = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 18)
ABF2.EpochPerDAC.def = data.frame(field = ABF2.EpochPerDAC.field,
                                 ctype = ABF2.EpochPerDAC.ctype,
                                 ssize = ABF2.EpochPerDAC.ssize)

ABF2.Epoch.field = c("nEpochNum",
                    "nDigitalValue",
                    "nDigitalTrainValue",
                    "nAlternateDigitalValue",
                    "nAlternateDigitalTrainValue",
                    "bEpochCompression",
                    "sUnused")
ABF2.Epoch.ctype = c("int16",
                    "int16",
                    "int16",
                    "int16",
                    "int16",
                    "int8",
                    "unused")
ABF2.Epoch.ssize = c(0, 0, 0, 0, 0, 0, 21)
ABF2.Epoch.def = data.frame(field = ABF2.Epoch.field,
                           ctype = ABF2.Epoch.ctype,
                           ssize = ABF2.Epoch.ssize)

ABF2.StatsRegion.field = c("nRegionNum",
                          "nADCNum",
                          "nStatsActiveChannels",
                          "nStatsSearchRegionFlags",
                          "nStatsSelectedRegion",
                          "nStatsSmoothing",
                          "nStatsSmoothingEnable",
                          "nStatsBaseline",
                          "lStatsBaselineStart",
                          "lStatsBaselineEnd",
                          "lStatsMeasurements",
                          "lStatsStart",
                          "lStatsEnd",
                          "nRiseBottomPercentile",
                          "nRiseTopPercentile",
                          "nDecayBottomPercentile",
                          "nDecayTopPercentile",
                          "nStatsSearchMode",
                          "nStatsSearchDAC",
                          "nStatsBaselineDAC",
                          "sUnused")
ABF2.StatsRegion.ctype = c( "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int32",
                           "int32",
                           "int32",
                           "int32",
                           "int32",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "int16",
                           "unused"  )
ABF2.StatsRegion.ssize = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 78)
ABF2.StatsRegion.def = data.frame(field = ABF2.StatsRegion.field,
                                 ctype = ABF2.StatsRegion.ctype,
                                 sszie = ABF2.StatsRegion.ssize)

ABF2.UserList.field = c("nListNum",
                       "nULEnable",
                       "nULParamToVary",
                       "nULRepeat",
                       "lULParamValueListIndex",
                       "sUnused")
ABF2.UserList.ctype = c("int16",
                       "int16",
                       "int16",
                       "int16",
                       "int32",
                       "unused")
ABF2.UserList.ssize = c(0, 0, 0, 0, 0, 52)
ABF2.UserList.def = data.frame(field = ABF2.UserList.field,
                              ctype = ABF2.UserList.ctype,
                              sszie = ABF2.UserList.ssize)
